version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_YOUTUBE_API_KEY=${REACT_APP_YOUTUBE_API_KEY}